participants = {"${bigBankCordaIdentity}" = "${bigBankAccount}"}
mints = {"${cordaTokenTypeLinearId}" = "${tokenMintAccount}"}
mintAuthorities = {"${cordaTokenTypeLinearId}" = "${bridgeAuthorityAccount}"}