configurations {
    testOutput
}

// Create a JAR of integrationTest classes to share with 'demo' module
tasks.register('testJar', Jar) {
    archiveClassifier = 'test'
    from sourceSets.test.output
}

// Expose integrationTest JAR to 'demo' module
artifacts {
    testOutput testJar
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"

    // Corda dependencies
    testImplementation "$corda_os_release_group:corda-core:$corda_os_release_version"
    testImplementation "$corda_enterprise_release_group:corda-node-driver:$corda_enterprise_release_version"
    testImplementation "$corda_enterprise_release_group:corda-core-test-utils:$corda_enterprise_release_version"

    // Corda - Solana dependencies
    testImplementation "net.corda.solana.notary:solana-notary-testing:$corda_solana_notary_version"
    testImplementation "com.r3.corda.lib.solana:corda-solana-testing:$corda_solana_toolkit_version"

    testImplementation "com.r3.corda.lib.tokens:tokens-contracts:$corda_tokens_release_version"

    testImplementation "com.r3.corda.lib.solana:bridge-authority-workflows:$corda_solana_toolkit_version"
    testImplementation "com.r3.corda.lib.solana:bridge-authority-contracts:$corda_solana_toolkit_version"

    testImplementation "com.stockpaydividend:contracts:1.0"
    testImplementation "com.stockpaydividend:workflows:1.0"
}

test {
    jvmArgs '--add-modules=jdk.incubator.foreign'
}
