cordaEnterpriseReleaseGroup=com.r3.corda
cordaOsReleaseGroup=net.corda
cordaEnterpriseVersion=4.14-RC03
cordaOsVersion=4.14-RC03
cordaSolanaNotaryVersion=0.2.5
cordaTokensVersion=1.3.2
cordaSolanaToolkitVersion=0.1.8
platformVersion=160
gradlePluginsVersion=5.1.1
kotlinVersion=1.9.25
junitVersion=4.13.2
junitJupiterVersion=5.14.3
log4jVersion=2.25.3
slf4jVersion=2.0.12
