cordaEnterpriseReleaseGroup=com.r3.corda
cordaOsReleaseGroup=net.corda
cordaEnterpriseVersion=4.14-20260202.004000-76
cordaOsVersion=4.14-20260129.000800-86
cordaSolanaNotaryVersion=0.2.0
cordaTokensVersion=1.3.2
savaVersion=25.1.2-j17-2
platformVersion=160
gradlePluginsVersion=5.1.1
kotlinVersion=1.9.20
junitVersion=4.12
log4jVersion=2.25.3
slf4jVersion=2.0.12
