repositories {
    mavenLocal()
    mavenCentral()

    maven { url 'https://download.corda.net/maven/corda-dependencies' }
    maven { url 'https://repo.gradle.org/gradle/libs-releases' }
    // Add required repositories for Corda artifacts
    // For Corda Core
    maven { url 'https://software.r3.com/artifactory/corda-dev'
        credentials {
            username = System.getenv('CORDA_ARTIFACTORY_USERNAME')
            password = System.getenv('CORDA_ARTIFACTORY_PASSWORD')
        }
    }
    // For Corda Node API
    maven { url 'https://software.r3.com/artifactory/r3-corda-dev'
        credentials {
            username = System.getenv('CORDA_ARTIFACTORY_USERNAME')
            password = System.getenv('CORDA_ARTIFACTORY_PASSWORD')
        }
    }
    maven {
        url 'https://software.r3.com/artifactory/r3-corda-releases'
        credentials {
            username = System.getenv('CORDA_ARTIFACTORY_USERNAME')
            password = System.getenv('CORDA_ARTIFACTORY_PASSWORD')
        }
    }
    // For Corda Tokens SDK
    maven { url 'https://software.r3.com/artifactory/corda-lib'
        credentials {
            username = System.getenv('CORDA_ARTIFACTORY_USERNAME')
            password = System.getenv('CORDA_ARTIFACTORY_PASSWORD')
        }
    }

    // TODO this is temporarily until toolkit '0.1.8' is release
    maven { url 'https://software.r3.com/artifactory/corda-dependencies-dev'
        credentials {
            username = System.getenv('CORDA_ARTIFACTORY_USERNAME')
            password = System.getenv('CORDA_ARTIFACTORY_PASSWORD')
        }
    }
}