plugins {
    id 'net.corda.plugins.cordapp'
    id 'com.adarshr.test-logger' version '4.0.0'
}

cordapp {
    targetPlatformVersion corda_platform_version.toInteger()
    minimumPlatformVersion corda_platform_version.toInteger()
    contract {
        name "Corda-Solana DvP Contracts"
        vendor "Corda Open Source"
        licence "Apache License, Version 2.0"
        versionId 1
    }
    signing {
        enabled true
    }
}

dependencies {
    implementation "com.r3.corda.lib.solana:corda-solana-cordapp-utils:$corda_solana_toolkit_version"

    // Corda dependencies.
    cordaProvided "$corda_os_release_group:corda-core:$corda_os_release_version"
    // Token SDK dependencies.
    cordaProvided "com.r3.corda.lib.tokens:tokens-contracts:$corda_tokens_release_version"

    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "$corda_enterprise_release_group:corda-node-driver:$corda_enterprise_release_version"
    testImplementation "$corda_enterprise_release_group:corda-test-utils:$corda_enterprise_release_version" // Enterprise dependency for notary instruction code
    testImplementation "$corda_os_release_group:corda-core-test-utils:$corda_os_release_version"
}
