dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"

    // Dependency on integration-tests module's integrationTest source set
    testImplementation project(path: ':integration-tests', configuration: 'testOutput')

    // Corda dependencies.
    testImplementation "$corda_os_release_group:corda-core:$corda_os_release_version"
    testImplementation "$corda_enterprise_release_group:corda-node-driver:$corda_enterprise_release_version"
    testImplementation "$corda_enterprise_release_group:corda-test-common:$corda_enterprise_release_version"

    testImplementation "com.r3.corda.lib.solana:bridge-authority-workflows:$corda_solana_toolkit_version"
    testImplementation "com.r3.corda.lib.solana:bridge-authority-contracts:$corda_solana_toolkit_version"

    testImplementation "com.stockpaydividend:contracts:1.0"
    testImplementation "com.stockpaydividend:workflows:1.0"
}

test {
    jvmArgs '--add-modules=jdk.incubator.foreign'
}
