plugins {
    id 'net.corda.plugins.cordapp'
    id 'net.corda.plugins.quasar-utils'
    id 'com.adarshr.test-logger' version '4.0.0'
}

cordapp {
    targetPlatformVersion corda_platform_version.toInteger()
    minimumPlatformVersion corda_platform_version.toInteger()
    workflow {
        name "Corda-Solana DvP Flows"
        vendor "Corda Open Source"
        licence "Apache License, Version 2.0"
        versionId 1
    }
}

sourceSets {
    main {
        resources {
            srcDir rootProject.file("config/dev")
        }
    }
    test {
        resources {
            srcDir rootProject.file("config/test")
        }
    }
    integrationTest {
        kotlin {
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
            srcDir file('src/integrationTest/kotlin')
        }
    }
}

configurations {
    integrationTestImplementation.extendsFrom testImplementation
    integrationTestRuntimeOnly.extendsFrom testRuntimeOny
}

dependencies {
    implementation "com.r3.corda.lib.solana:corda-solana-cordapp-utils:$corda_solana_toolkit_version"
    implementation "com.r3.corda.lib.solana:corda-solana-core:$corda_solana_toolkit_version"

    // CorDapp dependencies.
    cordapp project(":contracts")

    // Corda dependencies.
    cordaProvided "$corda_os_release_group:corda-core:$corda_os_release_version"
    cordaProvided "$corda_enterprise_release_group:corda-node:$corda_enterprise_release_version"
    // Token SDK dependencies.
    cordaProvided "com.r3.corda.lib.tokens:tokens-contracts:$corda_tokens_release_version"
    cordaProvided "com.r3.corda.lib.tokens:tokens-workflows:$corda_tokens_release_version"
    cordaProvided "com.github.ben-manes.caffeine:caffeine:$caffeine_version"

    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "$corda_enterprise_release_group:corda-node-driver:$corda_enterprise_release_version"
    testImplementation "$corda_enterprise_release_group:corda-core-test-utils:$corda_enterprise_release_version"
    testImplementation "net.corda.solana.notary:solana-notary-testing:$corda_solana_notary_version"
    testImplementation "com.r3.corda.lib.solana:corda-solana-testing:$corda_solana_toolkit_version"
}

test {
    jvmArgs '--add-modules=jdk.incubator.foreign'
}
